{
  "name": "System black theme",
  "description": "Black theme in \"automatic\" dark theme",
  "authors": [
    {
      "name": "Alazraq",
      "id": "1168156458010026015"
    }
  ],
  "spec": 2,
  "semanticColors": {
    "BACKGROUND_TERTIARY": ["#000000"],
    "BACKGROUND_ACCENT": ["#08080A"],
    "SPOILER_HIDDEN_BACKGROUND": ["#1E1F22"],
    "SPOILER_REVEALED_BACKGROUND": ["#232428"]
  },
  "rawColors": {
    "PRIMARY_560": "#08080A",
    "PRIMARY_600": "#000000",
    "PRIMARY_630": "#000000",
    "PRIMARY_660": "#08080A",
    "PRIMARY_700": "#08080A",
    "PRIMARY_800": "#08080A",

    "PLUM_15": "#08080A",
    "PLUM_17": "#000000",
    "PLUM_18": "#08080A",
    "PLUM_19": "#08080A",
    "PLUM_20": "#000000",
    "PLUM_23": "#000000",
    "PLUM_24": "#08080A"
  },
  "plus": {
    "version": "0",
    "iconpack": "md3"

   "background": {
    "blur": 0,
    "url": "https://media.discordapp.net/attachments/1168205604326735893/1294116954528944269/aizen.jpg?ex=6709d7d5&is=67088655&hm=5bf132c05b63fc9c13b9702a3d720606025ecc7ecf0c5eed59a8f68b47b6be93&",
    "alpha": 0.4
    },
    "color": "#4d4463"
}
